### ISSUE TITLE
Workflow

### ISSUE THREAD

**Issue by arnavs** [arnavs/QuantEcon.cheatsheet#1]
cc @jlperla @ajozefiak 

I added the new Julia stuff to the `draft-changes` branch of the repo (the `master` is currently being used for a PR on the pure Julia cheatsheet). 

Workflow is basically to edit the rST table directly. Matt suggested we use an rST table editor for our text editor, but haven't had the time to look into that yet. 

Basically, Adam- goal is to look for any cell with Julia content but no Python content and fill in the Python content. Be aware of whitespace, etc., and try to follow the style guide for the main lecture notes.

**Comment by arnavs** [comment]
Also @ajozefiak it may help to glance briefly at the [rST spec](http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html), since you said you hadn't worked with it before.

**Comment by arnavs** [comment]
Just to be clear, the job right now is to focus on the content without worrying about compilation. So maybe even a Jupyter notebook or m-file or Python script file would do, before we get guidance from Matt on syntax and tools

**Comment by jlperla** [comment]
@ajozefiak I am making modifications to `index.rst` for the julia and matlab stuff, and will ping this issue when I am done.

**Comment by jlperla** [comment]
I have added the matlab code, but I am sure the table is broken.  I have no idea how we will able to get this to format properly with RST, but lets get the python code in there first, and then we can figure out the best approach.

**Comment by ajozefiak** [comment]
I've submitted a pr #2 that has some of the python rows filled. I'm missing a few for which I'm not too sure about. 

For instance, with the sparse and tridiagonal matrices I believe numpy doesn't have support for such matrices and so scipy would be required.

**Comment by ajozefiak** [comment]
I've updated my branch/pr so that only the tridiagonal and sparse matrices are not implemented yet, due to my above comment. 

As well, for named tuples I used the collections library.

**Comment by arnavs** [comment]
Perfect, and that's fine so long as that's included with Python.
